name: line
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-243.0.dev

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^6.1.4
  email_validator: ^3.0.0
  firebase_auth: ^5.5.2
  firebase_core: ^3.13.0
  fluttertoast: ^8.2.12
  get: ^4.7.2
  intl: ^0.19.0
  logger: ^2.5.0
  path: ^1.9.1
  path_provider: ^2.1.5
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
